### ISSUE TITLE
🚀 Feature:  Migrate from travis.yml to Github actions

### ISSUE THREAD

**Issue by 2002Bishwajeet** [utopia-php/framework#103]
### 🔖 Feature description

As the title suggests, we are currently migrating all of our workflows from Travis to GitHub Actions. Here's the below checklist that needs to be migrated to GitHub Actions.

### Tasklist
- [x] utopia-php/ab ([#12](https://github.com/utopia-php/ab/pull/12))
- [x] utopia-php/analytics ([#45](https://github.com/utopia-php/analytics/pull/45))
- [x] utopia-php/cache ([#13](https://github.com/utopia-php/cache/pull/30))
- [x] utopia-php/cli ([#29](https://github.com/utopia-php/cli/pull/29))
- [x] utopia-php/config ([#12](https://github.com/utopia-php/config/pull/12))
- [x] utopia-php/domains ([#31](https://github.com/utopia-php/domains/pull/31))
- [x] utopia-php/image ([#27](https://github.com/utopia-php/image/pull/27))
- [x] utopia-php/locale ([#16](https://github.com/utopia-php/locale/pull/16))
- [x] utopia-php/logger  ([#30](https://github.com/utopia-php/logger/pull/30))
- [ ] utopia-php/mongo
- [x] utopia-php/orchestration ([#33](https://github.com/utopia-php/orchestration/pull/33))
- [ ] utopia-php/queue
- [x] utopia-php/registry ([#13](https://github.com/utopia-php/registry/pull/13))
- [ ] utopia-php/storage
- [x] utopia-php/system ([#24](https://github.com/utopia-php/system/pull/24))
- [ ] utopia-php/pay
- [ ] utopia-php/platform
- [ ] utopia-php/preloader
- [ ] utopia-php/websocket

You can look at one of the PRs attached to help us migrating to GitHub actions for rest of the repos

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by faisalill** [comment]
@2002Bishwajeet 
utopia-php/cache with https://github.com/utopia-php/cache/pull/30

**Comment by faisalill** [comment]
@2002Bishwajeet 
utopia-php/cli with https://github.com/utopia-php/cli/pull/29

**Comment by faisalill** [comment]
@2002Bishwajeet 
utopia-php/config => https://github.com/utopia-php/config/pull/12

**Comment by christyjacob4** [comment]
@sahilsaha7773 please work on domains, platform, orchestration & registry 

FYI @2002Bishwajeet @faisalill
